################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=DP-2, preferred, 3072x0, 1.25
monitor=DP-1, preferred, 0x0, 1.25

$leftMonitor = DP-1
$rightMonitor = DP-2
