--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-2",
    mode = "preferred",
    position = "3072x0",
    scale = "1.25",
})

hl.monitor({
    output = "DP-1",
    mode = "preferred",
    position = "0x0",
    scale = "1.25",
})

local leftMonitor = "DP-1"
local rightMonitor = "DP-2"
