--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
local leftMonitor = "HDMI-A-2"
local rightMonitor = "HDMI-A-1"


hl.monitor({
    output = rightMonitor,
    mode = "preferred",
    position = "1920x0",
    scale = "1",
})

hl.monitor({
    output = leftMonitor,
    mode = "preferred",
    position = "0x0",
    scale = "1",
})



--## Mouse Settings ###
hl.device({
    name = "ELECOM IST TrackBall",
    sensitivity = -0.75,
})

return {
    left = leftMonitor,
    right = rightMonitor,
}