--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
local leftMonitor = "DP-1"
local rightMonitor = "DP-2"

hl.monitor({
    output = rightMonitor,
    mode = "preferred",
    position = "3072x0",
    scale = "1.25",
})

hl.monitor({
    output = leftMonitor,
    mode = "preferred",
    position = "0x0",
    scale = "1.25",
})
return {
    left = leftMonitor,
    right = rightMonitor,
}
