-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/machine-specific/bl-laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("machine-specific.bl-laptop")
